map2gazebo:
  ros__parameters:
    # Topic that the map to convert is being published on
    map_topic: "map"
    # Can be "stl" or "dae"
    mesh_type: "dae"
    # Minimum threshold value for considering a map cell occupied
    occupied_thresh: 50
    # Height of boxes in gazebo environment
    box_height: -3.0 #2.0
    # Specify export_dir in this file as the launchfile will override it.
    export_dir: "{PATH_TO_MODULE}/map2gazebo/models/{MODEL_NAME}/meshes/"
